// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, force, forceSSL, fs, http, https, noCache, options, secureServer, server, vhost;

  express = require('express');

  app = express();

  force = require('express-force-domain');

  forceSSL = require('express-force-ssl');

  https = require('https');

  http = require('http');

  vhost = require('vhost');

  fs = require('fs');

  noCache = require('connect-nocache');

  options = {
    key: fs.readFileSync('./keys/libreado.com.key'),
    cert: fs.readFileSync('./keys/libreado.com.crt'),
    ca: fs.readFileSync('./keys/rootCA.crt')
  };

  app.use(forceSSL);

  app.use(require('connect-redirecthost').redirectHost({
    to: 'www.libreado.com',
    except: ['app.libreado.com', 'api.libreado.com']
  }));

  app.use(vhost('app.libreado.com', require('./sites/app')));

  app.use(vhost('www.libreado.com', require('./sites/www')));

  app.use(vhost('api.libreado.com', require('./sites/api')));

  secureServer = https.createServer(options, app);

  server = http.createServer(app);

  secureServer.listen(8443);

  server.listen(8080);

}).call(this);

//# sourceMappingURL=app.map
