// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, path, pub;

  express = require('express');

  path = require('path');

  app = express();

  pub = path.join(__dirname, '/public');

  app.use(express["static"](pub));

  app.set('views', "" + __dirname + "/views");

  app.set('view engine', 'jade');

  app.get('/', function(req, res) {
    return res.render('users', {
      users: {
        '111': '111'
      }
    });
  });

  app.use(function(err, req, res, next) {
    return res.send(err.stack);
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=index.map
