// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(config, mongoose) {
    var UserModel, UserSchema, createUser, showUsers;
    UserSchema = new mongoose.Schema({
      email: {
        type: String,
        unique: true
      },
      created: {
        type: Date,
        "default": Date.now
      }
    }, {
      strict: false
    });
    UserModel = mongoose.model("users", UserSchema);
    createUser = function(email) {
      var user;
      console.log(222);
      user = new UserModel;
      user.email = email;
      return user.save(function(err, doc) {
        return console.log(doc);
      });
    };
    showUsers = function() {
      return "pass";
    };
    return {
      model: UserModel,
      createUser: createUser
    };
  };

}).call(this);

//# sourceMappingURL=user.map
